name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: VirtusLab/scala-cli-setup@5b1a6c5ca98b5642996812781f6ad9b2d5935f85
        with:
          jvm: "temurin:17"
      - name: Generate Linux Launcher
        run: |
          .github/scripts/generate-native-image.sh
          ./mill -i copyDefaultLauncher artifacts/linux-launcher
      - name: Generate Mostly Static Launcher
        run: |
          .github/scripts/generate-native-image.sh mostly-static
          ./mill -i copyMostlyStaticLauncher artifacts/mostly-static-launcher
      - name: Generate Static Launcher  
        run: |
          .github/scripts/generate-native-image.sh static
          ./mill -i copyStaticLauncher artifacts/static-launcher
      - uses: actions/upload-artifact@v3
        with:
          name: launchers
          path: |
            artifacts/linux-launcher
            artifacts/mostly-static-launcher
            artifacts/static-launcher
  release:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: launchers
      - run: find .
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            linux-launcher
            mostly-static-launcher
            static-launcher
